### ISSUE TITLE
Favorites & Watchlist Components

### ISSUE THREAD

**Issue by Linuszackrisson** [Linuszackrisson/movie-db-react#25]
Favorites Component: En komponent som visar användarens favoritfilmer.

- [ ] **Funktion för att lägga till och ta bort filmer**
- [ ] **Använd Movie card componenten**

**Comment by isakskold** [comment]
Ska försöka skapa om funktionalitet för detta igen från scratch utan att använda Redux. Kommer bli enklare att förstå sig på koden. Redux bör inte användas för så simpla grejer som detta.
